/************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.5 Build 250402
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------
#define IN_PB0_PORT           B
#define IN_PB0_PIN            0
#define IN_PB0_GPIO_CLK      STRCAT2(P,          IN_PB0_PORT)
#define IN_PB0_GPIO_ID       STRCAT2(GPIO_P,     IN_PB0_PORT)
#define IN_PB0_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB0_PORT)
#define IN_PB0_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB0_PIN)
#define IN_PB0_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB0_STATE         (GPIO_ReadInBit(IN_PB0_GPIO_PORT, IN_PB0_GPIO_PIN))

#define IN_PB1_PORT           B
#define IN_PB1_PIN            1
#define IN_PB1_GPIO_CLK      STRCAT2(P,          IN_PB1_PORT)
#define IN_PB1_GPIO_ID       STRCAT2(GPIO_P,     IN_PB1_PORT)
#define IN_PB1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB1_PORT)
#define IN_PB1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB1_PIN)
#define IN_PB1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB1_STATE         (GPIO_ReadInBit(IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN))

#define IN_PB2_PORT           B
#define IN_PB2_PIN            2
#define IN_PB2_GPIO_CLK      STRCAT2(P,          IN_PB2_PORT)
#define IN_PB2_GPIO_ID       STRCAT2(GPIO_P,     IN_PB2_PORT)
#define IN_PB2_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB2_PORT)
#define IN_PB2_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB2_PIN)
#define IN_PB2_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB2_STATE         (GPIO_ReadInBit(IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN))

#define IN_PB3_PORT           B
#define IN_PB3_PIN            3
#define IN_PB3_GPIO_CLK      STRCAT2(P,          IN_PB3_PORT)
#define IN_PB3_GPIO_ID       STRCAT2(GPIO_P,     IN_PB3_PORT)
#define IN_PB3_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB3_PORT)
#define IN_PB3_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB3_PIN)
#define IN_PB3_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB3_STATE         (GPIO_ReadInBit(IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN))

#define IN_PB4_PORT           B
#define IN_PB4_PIN            4
#define IN_PB4_GPIO_CLK      STRCAT2(P,          IN_PB4_PORT)
#define IN_PB4_GPIO_ID       STRCAT2(GPIO_P,     IN_PB4_PORT)
#define IN_PB4_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PB4_PORT)
#define IN_PB4_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PB4_PIN)
#define IN_PB4_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PB4_STATE         (GPIO_ReadInBit(IN_PB4_GPIO_PORT, IN_PB4_GPIO_PIN))



//-----------------------------------------------------------------------------
#define OUT_PB7_PORT           B
#define OUT_PB7_PIN            7
#define OUT_PB7_GPIO_CLK      STRCAT2(P,          OUT_PB7_PORT)
#define OUT_PB7_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB7_PORT)
#define OUT_PB7_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB7_PORT)
#define OUT_PB7_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB7_PIN)
#define OUT_PB7_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB7_HIGH          OUT_PB7_GPIO_PORT->SRR    = OUT_PB7_GPIO_PIN
#define OUT_PB7_LOW           OUT_PB7_GPIO_PORT->RR     = OUT_PB7_GPIO_PIN
#define OUT_PB7_XOR           OUT_PB7_GPIO_PORT->DOUTR ^= OUT_PB7_GPIO_PIN
#define OUT_PB7_STATE        (GPIO_ReadInBit(OUT_PB7_GPIO_PORT, OUT_PB7_GPIO_PIN))

#define SOFT_SDA_PORT           B
#define SOFT_SDA_PIN            7
#define SOFT_SDA_GPIO_CLK      STRCAT2(P,          SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_ID       STRCAT2(GPIO_P,     SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_PORT     STRCAT2(HT_GPIO,    SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_PIN      STRCAT2(GPIO_PIN_,  SOFT_SDA_PIN)
#define SOFT_SDA_AFIO_MODE     (AFIO_MODE_GPIO)
#define SOFT_SDA_HIGH          SOFT_SDA_GPIO_PORT->SRR    = SOFT_SDA_GPIO_PIN
#define SOFT_SDA_LOW           SOFT_SDA_GPIO_PORT->RR     = SOFT_SDA_GPIO_PIN
#define SOFT_SDA_XOR           SOFT_SDA_GPIO_PORT->DOUTR ^= SOFT_SDA_GPIO_PIN
#define SOFT_SDA_STATE        (GPIO_ReadInBit(SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN))

#define OUT_PB8_PORT           B
#define OUT_PB8_PIN            8
#define OUT_PB8_GPIO_CLK      STRCAT2(P,          OUT_PB8_PORT)
#define OUT_PB8_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB8_PORT)
#define OUT_PB8_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB8_PORT)
#define OUT_PB8_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB8_PIN)
#define OUT_PB8_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB8_HIGH          OUT_PB8_GPIO_PORT->SRR    = OUT_PB8_GPIO_PIN
#define OUT_PB8_LOW           OUT_PB8_GPIO_PORT->RR     = OUT_PB8_GPIO_PIN
#define OUT_PB8_XOR           OUT_PB8_GPIO_PORT->DOUTR ^= OUT_PB8_GPIO_PIN

#define SOFT_SCL_PORT           B
#define SOFT_SCL_PIN            8
#define SOFT_SCL_GPIO_CLK      STRCAT2(P,          SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_ID       STRCAT2(GPIO_P,     SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_PORT     STRCAT2(HT_GPIO,    SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_PIN      STRCAT2(GPIO_PIN_,  SOFT_SCL_PIN)
#define SOFT_SCL_AFIO_MODE     (AFIO_MODE_GPIO)
#define SOFT_SCL_HIGH          SOFT_SCL_GPIO_PORT->SRR    = SOFT_SCL_GPIO_PIN
#define SOFT_SCL_LOW           SOFT_SCL_GPIO_PORT->RR     = SOFT_SCL_GPIO_PIN
#define SOFT_SCL_XOR           SOFT_SCL_GPIO_PORT->DOUTR ^= SOFT_SCL_GPIO_PIN

#define OUT_PB12_PORT           B
#define OUT_PB12_PIN            12
#define OUT_PB12_GPIO_CLK      STRCAT2(P,          OUT_PB12_PORT)
#define OUT_PB12_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB12_PORT)
#define OUT_PB12_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB12_PORT)
#define OUT_PB12_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB12_PIN)
#define OUT_PB12_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB12_HIGH          OUT_PB12_GPIO_PORT->SRR    = OUT_PB12_GPIO_PIN
#define OUT_PB12_LOW           OUT_PB12_GPIO_PORT->RR     = OUT_PB12_GPIO_PIN
#define OUT_PB12_XOR           OUT_PB12_GPIO_PORT->DOUTR ^= OUT_PB12_GPIO_PIN

#define OUT_PB13_PORT           B
#define OUT_PB13_PIN            13
#define OUT_PB13_GPIO_CLK      STRCAT2(P,          OUT_PB13_PORT)
#define OUT_PB13_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB13_PORT)
#define OUT_PB13_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB13_PORT)
#define OUT_PB13_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB13_PIN)
#define OUT_PB13_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB13_HIGH          OUT_PB13_GPIO_PORT->SRR    = OUT_PB13_GPIO_PIN
#define OUT_PB13_LOW           OUT_PB13_GPIO_PORT->RR     = OUT_PB13_GPIO_PIN
#define OUT_PB13_XOR           OUT_PB13_GPIO_PORT->DOUTR ^= OUT_PB13_GPIO_PIN

#define OUT_PB14_PORT           B
#define OUT_PB14_PIN            14
#define OUT_PB14_GPIO_CLK      STRCAT2(P,          OUT_PB14_PORT)
#define OUT_PB14_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB14_PORT)
#define OUT_PB14_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB14_PORT)
#define OUT_PB14_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB14_PIN)
#define OUT_PB14_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB14_HIGH          OUT_PB14_GPIO_PORT->SRR    = OUT_PB14_GPIO_PIN
#define OUT_PB14_LOW           OUT_PB14_GPIO_PORT->RR     = OUT_PB14_GPIO_PIN
#define OUT_PB14_XOR           OUT_PB14_GPIO_PORT->DOUTR ^= OUT_PB14_GPIO_PIN

//-----------------------------------------------------------------------------
// LED控制宏 (低电平点亮，高电平熄灭)
//-----------------------------------------------------------------------------
// 错误指示灯 (PB12)
#define LED_ERROR_ON          OUT_PB12_LOW      // 点亮错误灯
#define LED_ERROR_OFF         OUT_PB12_HIGH     // 熄灭错误灯
#define LED_ERROR_TOGGLE      OUT_PB12_XOR      // 翻转错误灯

// 状态1指示灯 (PB13)
#define LED_STATUS1_ON        OUT_PB13_LOW      // 点亮状态1灯
#define LED_STATUS1_OFF       OUT_PB13_HIGH     // 熄灭状态1灯
#define LED_STATUS1_TOGGLE    OUT_PB13_XOR      // 翻转状态1灯

// 状态2指示灯 (PB14)
#define LED_STATUS2_ON        OUT_PB14_LOW      // 点亮状态2灯
#define LED_STATUS2_OFF       OUT_PB14_HIGH     // 熄灭状态2灯
#define LED_STATUS2_TOGGLE    OUT_PB14_XOR      // 翻转状态2灯


//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif
