/************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.5 Build 250402
//-----------------------------------------------------------------------------
#include "GPIO.h"

//-----------------------------------------------------------------------------
void GPIO_Configuration(void)
{
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.PB    = 1;
  CKCUClock.Bit.AFIO  = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);


  AFIO_GPxConfig         (OUT_PB12_GPIO_ID, OUT_PB12_GPIO_PIN, AFIO_FUN_GPIO);

  AFIO_GPxConfig         (OUT_PB13_GPIO_ID, OUT_PB13_GPIO_PIN, AFIO_FUN_GPIO);

  AFIO_GPxConfig         (OUT_PB14_GPIO_ID, OUT_PB14_GPIO_PIN, AFIO_FUN_GPIO);

  // 配置按键引脚AFIO功能
  AFIO_GPxConfig         (IN_PB0_GPIO_ID, IN_PB0_GPIO_PIN, AFIO_FUN_GPIO);
  AFIO_GPxConfig         (IN_PB1_GPIO_ID, IN_PB1_GPIO_PIN, AFIO_FUN_GPIO);
  AFIO_GPxConfig         (IN_PB2_GPIO_ID, IN_PB2_GPIO_PIN, AFIO_FUN_GPIO);
  AFIO_GPxConfig         (IN_PB3_GPIO_ID, IN_PB3_GPIO_PIN, AFIO_FUN_GPIO);
  AFIO_GPxConfig         (IN_PB4_GPIO_ID, IN_PB4_GPIO_PIN, AFIO_FUN_GPIO);

  GPIO_DirectionConfig    (IN_PB0_GPIO_PORT, IN_PB0_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB0_GPIO_PORT, IN_PB0_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB0_GPIO_PORT, IN_PB0_GPIO_PIN, GPIO_PR_UP);

  GPIO_DirectionConfig    (IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB1_GPIO_PORT, IN_PB1_GPIO_PIN, GPIO_PR_UP);

  GPIO_DirectionConfig    (IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB2_GPIO_PORT, IN_PB2_GPIO_PIN, GPIO_PR_UP);

  GPIO_DirectionConfig    (IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB3_GPIO_PORT, IN_PB3_GPIO_PIN, GPIO_PR_UP);

  GPIO_DirectionConfig    (IN_PB4_GPIO_PORT, IN_PB4_GPIO_PIN, GPIO_DIR_IN);
  GPIO_InputConfig        (IN_PB4_GPIO_PORT, IN_PB4_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (IN_PB4_GPIO_PORT, IN_PB4_GPIO_PIN, GPIO_PR_UP);


  GPIO_SetOutBits         (SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN);
  GPIO_DirectionConfig    (SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN, GPIO_DIR_OUT);
  GPIO_InputConfig        (SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN, ENABLE);
  GPIO_OpenDrainConfig    (SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN, GPIO_PR_UP);

  GPIO_SetOutBits         (SOFT_SCL_GPIO_PORT, SOFT_SCL_GPIO_PIN);
  GPIO_DirectionConfig    (SOFT_SCL_GPIO_PORT, SOFT_SCL_GPIO_PIN, GPIO_DIR_OUT);
  GPIO_OpenDrainConfig    (SOFT_SCL_GPIO_PORT, SOFT_SCL_GPIO_PIN, ENABLE);
  GPIO_PullResistorConfig (SOFT_SCL_GPIO_PORT, SOFT_SCL_GPIO_PIN, GPIO_PR_UP);

  GPIO_ClearOutBits       (OUT_PB12_GPIO_PORT, OUT_PB12_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PB12_GPIO_PORT, OUT_PB12_GPIO_PIN, GPIO_DIR_OUT);

  GPIO_ClearOutBits       (OUT_PB13_GPIO_PORT, OUT_PB13_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PB13_GPIO_PORT, OUT_PB13_GPIO_PIN, GPIO_DIR_OUT);

  GPIO_ClearOutBits       (OUT_PB14_GPIO_PORT, OUT_PB14_GPIO_PIN);
  GPIO_DirectionConfig    (OUT_PB14_GPIO_PORT, OUT_PB14_GPIO_PIN, GPIO_DIR_OUT);
}

//-----------------------------------------------------------------------------



