 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.5 Build 250402
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
#define OUT_PB7_PORT           B
#define OUT_PB7_PIN            7
#define OUT_PB7_GPIO_CLK      STRCAT2(P,          OUT_PB7_PORT)
#define OUT_PB7_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB7_PORT)
#define OUT_PB7_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB7_PORT)
#define OUT_PB7_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB7_PIN)
#define OUT_PB7_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB7_HIGH          OUT_PB7_GPIO_PORT->SRR    = OUT_PB7_GPIO_PIN
#define OUT_PB7_LOW           OUT_PB7_GPIO_PORT->RR     = OUT_PB7_GPIO_PIN
#define OUT_PB7_XOR           OUT_PB7_GPIO_PORT->DOUTR ^= OUT_PB7_GPIO_PIN
#define OUT_PB7_STATE        (GPIO_ReadInBit(OUT_PB7_GPIO_PORT, OUT_PB7_GPIO_PIN))

#define SOFT_SDA_PORT           B
#define SOFT_SDA_PIN            7
#define SOFT_SDA_GPIO_CLK      STRCAT2(P,          SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_ID       STRCAT2(GPIO_P,     SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_PORT     STRCAT2(HT_GPIO,    SOFT_SDA_PORT)
#define SOFT_SDA_GPIO_PIN      STRCAT2(GPIO_PIN_,  SOFT_SDA_PIN)
#define SOFT_SDA_AFIO_MODE     (AFIO_MODE_GPIO)
#define SOFT_SDA_HIGH          SOFT_SDA_GPIO_PORT->SRR    = SOFT_SDA_GPIO_PIN
#define SOFT_SDA_LOW           SOFT_SDA_GPIO_PORT->RR     = SOFT_SDA_GPIO_PIN
#define SOFT_SDA_XOR           SOFT_SDA_GPIO_PORT->DOUTR ^= SOFT_SDA_GPIO_PIN
#define SOFT_SDA_STATE        (GPIO_ReadInBit(SOFT_SDA_GPIO_PORT, SOFT_SDA_GPIO_PIN))

#define OUT_PB8_PORT           B
#define OUT_PB8_PIN            8
#define OUT_PB8_GPIO_CLK      STRCAT2(P,          OUT_PB8_PORT)
#define OUT_PB8_GPIO_ID       STRCAT2(GPIO_P,     OUT_PB8_PORT)
#define OUT_PB8_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PB8_PORT)
#define OUT_PB8_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PB8_PIN)
#define OUT_PB8_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PB8_HIGH          OUT_PB8_GPIO_PORT->SRR    = OUT_PB8_GPIO_PIN
#define OUT_PB8_LOW           OUT_PB8_GPIO_PORT->RR     = OUT_PB8_GPIO_PIN
#define OUT_PB8_XOR           OUT_PB8_GPIO_PORT->DOUTR ^= OUT_PB8_GPIO_PIN

#define SOFT_SCL_PORT           B
#define SOFT_SCL_PIN            8
#define SOFT_SCL_GPIO_CLK      STRCAT2(P,          SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_ID       STRCAT2(GPIO_P,     SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_PORT     STRCAT2(HT_GPIO,    SOFT_SCL_PORT)
#define SOFT_SCL_GPIO_PIN      STRCAT2(GPIO_PIN_,  SOFT_SCL_PIN)
#define SOFT_SCL_AFIO_MODE     (AFIO_MODE_GPIO)
#define SOFT_SCL_HIGH          SOFT_SCL_GPIO_PORT->SRR    = SOFT_SCL_GPIO_PIN
#define SOFT_SCL_LOW           SOFT_SCL_GPIO_PORT->RR     = SOFT_SCL_GPIO_PIN
#define SOFT_SCL_XOR           SOFT_SCL_GPIO_PORT->DOUTR ^= SOFT_SCL_GPIO_PIN



//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif

