 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.5 Build 250402
//-----------------------------------------------------------------------------
#include "GPIO.h"      // GPIO引脚配置 (PB7, PB8作为软件I2C)
#include "BFTM0.h"     // 基本定时器 (100ms中断)
#include "UART0.h"     // 串口通信
#include "Soft_I2c.h"  // 软件I2C + TM1640数码管驱动

int main(void)
{
    // 4组显示数据 - 初始值设置为能展示小数点切换的范围
    float power = 0;        // 功率 (0-999)
    float  time_min = 0;      // 时间/分钟 (0-99)
    float env_temp = 0;     // 环境温度 (0-999)
    float self_temp = 0;    // 自身温度 (0-999)

    // 系统初始化
    GPIO_Configuration();   // 初始化GPIO引脚 (PB7=SDA, PB8=SCL)
    BFTM0_Configuration();  // 初始化定时器 (每100ms触发一次中断，bftm0_ct++)
    UART0_Configuration();  // 初始化串口 (115200波特率)

    TM1640_Init();  // 初始化TM1640数码管 (清屏、设置亮度、打开显示)

    // 主循环
    while(1)
    {
        // 每1秒执行一次 (bftm0_ct每100ms加1，累计到10即1秒)
        if(bftm0_ct >= 10)
        {
            bftm0_ct = 0;  // 重置计数器

            // 在数码管上显示4组数据
            TM1640_DisplayMultiData(power, time_min, env_temp, self_temp);

            // 递增并循环（演示小数点的动态显示）
            power+=0.1;
            if(power > 999) power = 0;  // 80-120范围，可以看到99->100时小数点消失

            time_min+=0.1;
            if(time_min > 99) time_min = 0;  // 0-15范围，可以看到9->10时的变化

            env_temp+=0.1;
            if(env_temp > 999) env_temp = 0;  // 85-110范围，可以看到99->100时小数点消失

            self_temp+=0.1;
            if(self_temp > 999) self_temp = 0;  // 90-105范围，可以看到99->100时小数点消失
        }
    }
}
